### PR TITLE
Enable HTTPS

### PR DESCRIPTION
**Pull request by venimus**
Use ssl-cert role to create certificate and enable in nginx

### CODE REVIEW

**Comment by venimus** [comment]
@dincho review

**Comment by dincho** [comment]
1. What's the use case?
2. [Ansible Role](https://github.com/jdauphant/ansible-role-nginx/blob/master/README.md#8-example-to-use-this-role-with-my-ssl-certs-role-to-generate-or-copie-ssl-certificate--httpsgalaxyansiblecomlistroles3115-) looks much better to me:

**Comment by venimus** [comment]
1. One common use case is to be able to use location services which require HTTPS
2. Refactored it with the role

**Comment by dincho** [comment]
I hope you're testing all of this

**Pull request merged**
