### PR TITLE
Update nbz4live.php-fpm role to version 2.0.9

### PR DESCRIPTION
**Pull request by KristiyanHristov**

### CODE REVIEW

**Comment by dincho** [comment]
What's the reason ?

**Comment by KristiyanHristov** [comment]
> What's the reason ?

```failed: [dev] (item=[u'php_fpm_apt_packages']) => {"changed": false, "failed": true, "item": ["php_fpm_apt_packages"], "msg": "No package matching 'php_fpm_apt_packages' is available"}```

`php_fpm_apt_packages` is not a package but part of the role configuration

**Comment by dincho** [comment]
Still don't get it, hopefully you tested it and it works.

**Comment by KristiyanHristov** [comment]
1. There is no version tagged "0.2.14"
2. https://github.com/NBZ4live/ansible-php-fpm/issues/19

**Pull request merged**
